[EHN]Like Gmail, warn if you are about to reply to a new contact (and perh…
cypht-org/cypht pull request #1065
Opened 2024-06-05 09:29 UTC by christer77

Feature to validate CC contacts if they exist in the user contact list. Being default, if the user disables this setting, will no longer be notified before the message is sent.

2024-06-19 05:18 UTC, Shadow243 requested changes
@marclaporte is it enough to just give an alert? we could make it possible to send by directly recording the contact instead of just alerting.

2024-06-19 11:31 UTC, marclaporte commented
> is it enough to just give an alert

So alert the first time, and after it's recorded as a approved recipient?

2024-07-01 12:29 UTC, Shadow243 commented
> > is it enough to just give an alert
> 
> So alert the first time, and after it's recorded as a approved recipient?

Yes

2024-07-05 08:04 UTC, christer77 commented
> @marclaporte is it enough to just give an alert? we could make it possible to send by directly recording the contact instead of just alerting.

Hello @Shadow243, @marclaporte 

Please enable this and see if it doesn't match your suggestion.

![add-automaticaly-adresse-in-contact-list](https://github.com/cypht-org/cypht/assets/62720246/b845272c-1154-4772-9083-fe16aeb796db)

2024-08-22 21:29 UTC, merged