[FIX] I fixed a PHP Warning  added a condition to check if ->get('rec…
cypht-org/cypht pull request #1128
Opened 2024-07-22 12:52 UTC by amaninyumu1

2024-08-01 15:20 UTC, Shadow243 commented
@amaninyumu1  Can you describe the scenario please !

2024-08-02 10:23 UTC, amaninyumu1 commented
Hello @Shadow243 
The problem was that we were trying to use $this->get('recaptcha_config') without being able to check if it exists. So I added a condition to check if it exists and then use it
return '<div class="g-recaptcha" data-sitekey="'.$this->html_safe($this->get('recaptcha_config')['site_key']).'"></div>';

2024-08-02 11:40 UTC, Shadow243 requested changes
According to https://github.com/cypht-org/cypht/blob/master/modules/recaptcha/setup.php#L8 `$this->get('recaptcha_config')` will never be undefined, did you get an issue about it ?

The file https://github.com/cypht-org/cypht/blob/master/modules/recaptcha/recaptcha.ini should be removed as well.

2024-08-02 19:05 UTC, amaninyumu1 commented
Yes but in this scenario the error was that the "recaptcha_config" key is null so it was impossible to access array offset on value of type null which is why I checked if it exists. In case it exists then it is not null

2024-08-02 19:18 UTC, Shadow243 commented
> The file https://github.com/cypht-org/cypht/blob/master/modules/recaptcha/recaptcha.ini should be removed as well.

Remove this please

2024-08-03 08:12 UTC, amaninyumu1 commented
I deleted this file https://github.com/cypht-org/cypht/blob/master/modules/recaptcha/recaptcha.ini

2024-08-03 10:56 UTC, Shadow243 commented
> I deleted this file https://github.com/cypht-org/cypht/blob/master/modules/recaptcha/recaptcha.ini

Delete it from the projet not form the PR.

2024-08-03 11:06 UTC, Shadow243 commented on modules/recaptcha/modules.php
> +        if (!$this->get('router_login_state') && $this->get('recaptcha_config')) {
use the condition like it's used here: https://github.com/cypht-org/cypht/blob/master/modules/recaptcha/modules.php#L16C9-L17C55

you can put the same condition at this level too: Hm_Output_recaptcha_script(https://github.com/cypht-org/cypht/blob/master/modules/recaptcha/modules.php#L46)

2024-08-03 12:28 UTC, amaninyumu1 commented on modules/recaptcha/modules.php
> +            return '<div class="g-recaptcha" data-sitekey="'.$this->html_safe($this->get('recaptcha_config')['site_key']).'"></div>';
this error comes back when I remove the condition that I put
[Sun Jul 21 11:18:55.635757 2024] [php:warn] [pid 1948:tid 1952] [client ::1:7190] PHP Warning:  Trying to access array offset on value of type null in C:\\xampp\\htdocs\\my_cypht\\modules\\recaptcha\\modules.php on line 59

2024-08-03 12:42 UTC, amaninyumu1 commented
if (!$this->get('router_login_state')) {
            $rconf = $this->get('recaptcha_config');
            if (is_array($rconf) && array_key_exists('site_key', $rconf) && $rconf['site_key']) {
                return '<div class="g-recaptcha" data-sitekey="'.$this->html_safe($this->get('recaptcha_config')['site_key']).'"></div>';
            }
        }

2024-08-03 13:20 UTC, Shadow243 commented
I just added the same condition at the recaptcha script level to prevent the js file from being reloaded: `https://www.google.com/recaptcha/api.js` when we don't need it.

You can test to see if there will be an error (in console and in logs)

2024-08-03 14:07 UTC, amaninyumu1 commented
yes it works

2024-08-03 17:02 UTC, merged