[UPD]composer.json: composer create-project installing older version
cypht-org/cypht pull request #943
Opened 2024-04-10 13:57 UTC by christer77

[related issue](https://github.com/cypht-org/cypht/issues/940)

2024-04-13 17:55 UTC, Shadow243 requested changes
I actually see version 4.17 with bug fixes and some good reactions. Seems like they're making steady improvements.

[https://github.com/ezyang/htmlpurifier/releases](https://github.com/ezyang/htmlpurifier/releases)

2024-04-14 12:41 UTC, marclaporte commented
@Shadow243 Since composer.json has "ezyang/htmlpurifier": "^4.16", it should get 4.17, 4.18, etc. right?

2024-04-14 12:44 UTC, marclaporte commented
Yes, we are already getting: https://github.com/cypht-org/cypht/blob/master/composer.lock#L249

@christer77 I don''t understand how this MR fixes the issue

2024-04-16 13:24 UTC, Shadow243 commented on composer.json
> +        "ezyang/htmlpurifier": "^4.16",
@christer77  Can you add composer.lock to this PR please!

2024-04-17 18:26 UTC, marclaporte commented on composer.lock
ezyang/htmlpurifier doesn't change in composer.lock

2024-04-19 11:23 UTC, merged